Repository rust-lang/rfcs, pull requests merged in 2018-11, with the labels that each got.

#2561 Meta-RFC: Future possibilities
  0000-template.md
  text/2561-future-possibilities.md
Labels: T-core, disposition-merge, finished-final-comment-period

#2589 Update 2116-alloc-me-maybe.md
  text/2116-alloc-me-maybe.md
Labels: not-rfc

#2500 RFC: Needle API (née Pattern API)
  text/2500-needle.md
Labels: A-needle, A-traits-libstd, A-types-libstd, T-libs, disposition-merge, finished-final-comment-period

#2591 Stabilise exhaustive integer pattern matching
  text/2591-exhaustive-integer-pattern-matching.md
Labels: A-exhaustiveness, A-patterns, A-primitive, T-lang, disposition-merge, finished-final-comment-period
