Repository rust-lang/rfcs, pull requests merged in 2018-08, with the labels that each got.

#2510 update ManuallyDrop RFC to reflect how the implementation now looks
  text/1860-manually-drop.md
Labels: T-lang

#2351 RFC: Add `is_sorted` to the standard library
  text/2351-is-sorted.md
Labels: T-libs, disposition-merge, finished-final-comment-period

#2504 Fix the Error trait
  text/2504-fix-error.md
Labels: T-libs, disposition-merge, finished-final-comment-period

#2229 Closures Capture Disjoint Fields
  text/2229-capture-disjoint-fields.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2497 eRFC: if- and while-let-chains, take 2
  text/2497-if-let-chains.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2521 Unify std::os::raw::c_void and libc::c_void via libcore
  text/0000-c_void-reunification.md
Labels: T-libs, disposition-merge, finished-final-comment-period
