Repository rust-lang/rfcs, pull requests merged in 2018-07, with the labels that each got.

#2493 Rename 2071-impl-trait-type-alias.md to 2071-impl-trait-existential-types.md
  text/2071-impl-trait-existential-types.md
  text/2071-impl-trait-type-alias.md
Labels: bug-fix

#2397 Introduce `#[do_not_recommend]` to control errors for trait impls
  text/2397-do-not-recommend.md
Labels: T-compiler, T-lang, disposition-merge, finished-final-comment-period

#2302 RFC: Tuple struct construction with `Self(v1, v2, ..)`
  text/2302-tuple-struct-self-ctor.md
Labels: T-lang, finished-final-comment-period

#2296 RFC: Add `Option::replace` to the core library
  text/2296-option-replace.md
Labels: T-libs, disposition-merge, finished-final-comment-period

#2344 Allow `loop` in constant evaluation
  text/2344-const-looping.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2478 Update RFC 0430 to allow underscores between numbers in CamelCase names
  text/0430-finalizing-naming-conventions.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2501 Fix link in RFC template and stuff
  0000-template.md
Labels: bug-fix

#2289 RFC: Associated type bounds of form `MyTrait<AssociatedType: Bounds>`
  text/2289-associated-type-bounds.md
Labels: T-lang, disposition-merge, finished-final-comment-period
