Repository rust-lang/rfcs, pull requests merged in 2018-10, with the labels that each got.

#2555 RFC 1268, fix feature name
  text/1268-allow-overlapping-impls-on-marker-traits.md
Labels: not-rfc

#2556 Convert raw-string URLs to Markdown
  text/2169-euclidean-modulo.md
  text/2226-fmt-debug-hex.md
  text/2230-bury-description.md
  text/2314-roadmap-2018.md
  text/2394-async_await.md
Labels: not-rfc

#2539 #[cfg_attr] expanding to multiple attributes
  text/2539-cfg_attr-multiple-attrs.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2412 The optimize attribute
  text/2412-optimize-attr.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2535 RFC: Or patterns, i.e `Foo(Bar(x) | Baz(x))`
  text/2535-or-patterns.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2526 Support underscores as constant names
  text/2526-const-wildcard.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2560 cfg-attr-multi: Fix typo
  text/2539-cfg_attr-multiple-attrs.md
Labels: not-rfc

#2476 Clippy 1.0
  text/2476-clippy-uno.md
Labels: T-dev-tools, disposition-merge, finished-final-comment-period

#2575 Make RFC 2476 conform to template
  text/2476-clippy-uno.md
Labels: not-rfc

#2451 Re-Rebalancing Coherence
  text/2451-re-rebalancing-coherence.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2457 Allow non-ASCII identifiers
  text/2457-non-ascii-idents.md
Labels: T-lang, disposition-merge, finished-final-comment-period
