Repository rust-lang/rfcs, pull requests merged in 2018-05, with the labels that each got.

#2230 Bury Error::description()
  0000-bury-description.md
Labels: T-libs

#2388 RFC: Reserve `try` for `try { .. }` block expressions
  text/2388-try-expr.md
Labels: T-lang, finished-final-comment-period

#2394 async/await notation for ergonomic asynchronous IO
  text/2394-async_await.md
Labels: T-lang, finished-final-comment-period

#2435 Fix typo in RFC 2000
  text/2000-const-generics.md
Labels: bug-fix

#2420 RFC: Unreserve `proc`
  text/2420-unreserve-proc.md
Labels: T-lang, finished-final-comment-period

#2386 RFC: #[used] static variables
  text/2386-used.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2421 RFC: Keyword unreservations (pure, sizeof, alignof, offsetof)
  text/2421-unreservations-2018.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2389 Clarify we mean UpperCamelCase, not lowerCamelCase
  text/0430-finalizing-naming-conventions.md
Labels: T-doc

#2405 Unstable features accidentally usable on the Stable release chanel are still unstable
  text/1105-api-evolution.md
Labels: T-core, finished-final-comment-period
