Repository rust-lang/rfcs, pull requests merged in 2018-04, with the labels that each got.

#2338 Type alias enum variants
  text/2338-type-alias-enum-variants.md
Labels: T-lang, final-comment-period

#2392 Correct typos
  text/2349-pin.md
Labels: bug-fix

#2295 RFC: Extend Pattern API to OsStr
  text/2295-os-str-pattern.md
Labels: T-libs, final-comment-period

#2196 metabuild: semantic build scripts for Cargo
  text/2196-metabuild.md
Labels: T-cargo, final-comment-period

#2102 Unnamed fields of struct and union type
  text/2102-unnamed-fields.md
Labels: T-lang, final-comment-period

#2387 Unapprove placement RFCs
  text/0809-box-and-in-for-stdlib.md
  text/1228-placement-left-arrow.md
Labels: I-nominated, T-lang

#2403 Fix a typo
  text/2342-const-control-flow.md
Labels: bug-fix

#2422 Fix runaway <code> in RFC 92: struct grammar
  text/0092-struct-grammar.md
Labels: bug-fix

#2423 RFC 2349: Conform to header format
  text/2349-pin.md
Labels: bug-fix

#2318 eRFC: Custom test frameworks
  text/2318-custom-test-frameworks.md
Labels: T-cargo, T-dev-tools, final-comment-period
