Repository rust-lang/rfcs, pull requests merged in 2018-02, with the labels that each got.

#2195 Formally define repr(u32, i8, etc...) and repr(C) on enums with payloads
  text/2195-really-tagged-unions.md
Labels: T-lang, final-comment-period

#2056 Allow trivial constraints to appear in where clauses
  text/2056-allow-trivial-where-clause-constraints.md
Labels: T-lang, final-comment-period

#2175 RFC: or-patterns in if / while let expressions
  text/2175-if-while-or-patterns.md
Labels: T-lang, final-comment-period

#2166 impl-only-use
  text/2166-impl-only-use.md
Labels: T-lang, final-comment-period

#2299 Issues are not feature requests
  README.md
Labels: T-core, final-comment-period

#2325 Stable SIMD in Rust
  text/2325-stable-simd.md
Labels: T-libs, final-comment-period

#2226 Hexadecimal integers with fmt::Debug, including within larger types
  text/2226-fmt-debug-hex.rs
Labels: T-libs, final-comment-period

#2151 RFC: Raw Identifiers
  text/2151-raw-identifiers.md
Labels: T-lang, final-comment-period

#2298 RFC: `?` repetition in macro rules
  text/2298-macro-at-most-once-rep.md
Labels: T-lang, final-comment-period

#2046 RFC: label-break-value
  text/0000-label-break-value.md
Labels: T-lang, final-comment-period

#2333 Meta-RFC: Prior art
  0000-template.md
  text/2333-prior-art.md
Labels: T-core, final-comment-period

#2250 mini-RFC: Finalize syntax of `impl Trait` and `dyn Trait` with multiple bounds
  text/2250-finalize-impl-dyn-syntax.md
Labels: T-lang, final-comment-period

#2354 fix filename extension typo
  text/2226-fmt-debug-hex.md
Labels: bug-fix

#2352 typo in rfc1216
  text/1216-bang-type.md
Labels: bug-fix
