Repository rust-lang/rfcs, pull requests merged in 2018-03, with the labels that each got.

#2282 Cargo profile dependencies
  text/2282-profile-dependencies.md
Labels: T-cargo, final-comment-period

#2314 RFC: Rust 2018 Roadmap
  text/2314-roadmap-2018.md
Labels: T-core, final-comment-period

#2341 Allow locals and destructuring in const fn
  text/2341-const-locals.md
Labels: T-lang, final-comment-period

#2285 Update the disambiguation handling in RFC 1946 (intra-rustdoc-links) to match impl concerns
  text/1946-intra-rustdoc-links.md
Labels: T-dev-tools, T-dev-tools-rustdoc, final-comment-period

#2169 Euclidean modulo
  text/2169-euclidean-modulo.md
Labels: T-libs, final-comment-period

#2307 RFC: Add std::num::NonZeroU32 and friends, deprecate core::nonzero
  text/2307-concrete-nonzero-types.md
Labels: T-libs, final-comment-period

#2342 Allow `if` and `match` in constants
  text/2342-const-control-flow.md
Labels: T-lang, final-comment-period

#2203 RFC: Constants in array repeat expressions
  text/2203-const-repeat-expr.md
Labels: T-lang, final-comment-period

#2349 Standard library API for immovable types
  text/0000-pin.md
Labels: T-libs, final-comment-period

#2365 Fix pseudocode typo in RFC 1951
  text/1951-expand-impl-trait.md
Labels: bug-fix

#2372 Typo: Change exists to exist in template.md#prior-art
  0000-template.md
Labels: bug-fix

#2373 Typo 2: Change exists to exist in template.md#prior-art [prior art RFC]
  text/2333-prior-art.md
Labels: bug-fix
