Repository rust-lang/rfcs, pull requests merged in 2019-07, with the labels that each got.

#2696 Add key and value methods to DebugMap
  text/2696-debug-map-key-value.md
Labels: A-fmt, T-libs, disposition-merge, finished-final-comment-period

#2720 Improve wording in the README
  README.md
Labels: not-rfc

#2726 Fix typo in 1291-promote-libc.md
  text/1291-promote-libc.md
Labels: not-rfc

#2515 Permit impl Trait in type aliases
  text/2515-impl-trait-type-aliases.md
Labels: A-impl-trait, A-syntax, A-traits, A-type-alias, A-typesystem, T-lang, disposition-merge, finished-final-comment-period

#2574 RFC: SIMD vectors in FFI
  text/2574-simd-ffi.md
Labels: A-ffi, A-simd, A-typesystem, T-compiler, T-lang, disposition-merge, finished-final-comment-period

#2733 typo
  text/2504-fix-error.md
Labels: not-rfc

#2734 Recommend Discord for discussion before creating RFCs instead of IRC channel
  README.md
Labels: not-rfc
