Repository rust-lang/rfcs, pull requests merged in 2019-04, with the labels that each got.

#2480 RFC: Stabilize the alloc crate
  text/2480-liballoc.md
Labels: T-libs, disposition-merge, finished-final-comment-period

#2681 Control-flow within a function: incorrect example
  text/2094-nll.md
Labels: T-lang, not-rfc

#2683 META: Replace "epoch" with "edition"
  text/2052-epochs.md
  text/2103-tool-attributes.md
  text/2113-dyn-trait-syntax.md
  text/2115-argument-lifetimes.md
  text/2126-path-clarity.md
  text/2151-raw-identifiers.md
  text/2314-roadmap-2018.md
Labels: not-rfc

#2687 Add a link to an RFC cross reference
  text/0769-sound-generic-drop.md
Labels: not-rfc

#2694 Add a link to the Futures RFC from the async/await RFC
  text/2394-async_await.md
Labels: not-rfc

#2645 Transparent Unions and Enums
  text/2645-transparent-unions.md
Labels: A-enum, A-ffi, A-repr, A-unions, T-lang, disposition-merge, finished-final-comment-period

#2565 RFC: Attributes in formal function parameter position
  text/2565-formal-function-parameter-attributes.md
Labels: A-attributes, A-syntax, T-lang, disposition-merge, finished-final-comment-period
