Repository rust-lang/rfcs, pull requests merged in 2019-09, with the labels that each got.

#2360 RFC: hint::bench_black_box
  text/2360-bench-black-box.md
Labels: A-hint, A-profiling, T-compiler, T-libs, disposition-merge, finished-final-comment-period

#2760 Fix typo
  text/2394-async_await.md
Labels: not-rfc

#2582 RFC for an operator to take a raw reference
  text/2582-raw-reference-mir-operator.md
Labels: A-machine, A-typesystem, A-unsafe, T-lang, disposition-merge, finished-final-comment-period

#2764 raw ref: mention why the more obvious syntax does not work
  text/2582-raw-reference-mir-operator.md
Labels: not-rfc

#2772 fix one typo
  text/0002-rfc-process.md
Labels: not-rfc

#2523 RFC: #[cfg(accessible(..) / version(..))]
  text/1105-api-evolution.md
  text/1122-language-semver.md
  text/2523-cfg-path-version.md
Labels: A-cfg, A-paths, A-versioning, T-lang, disposition-merge, finished-final-comment-period
