Repository rust-lang/rfcs, pull requests merged in 2019-02, with the labels that each got.

#2570 RFC: Linked list cursors
  text/2570-linked-list-cursors.md
Labels: A-collections, A-types-libstd, T-libs, disposition-merge, finished-final-comment-period

#2641 Typos in GAT RFC
  text/1598-generic_associated_types.md
Labels: not-rfc

#2627 #[link(kind="raw-dylib")]
  text/0000-raw-dylib-kind.md
Labels: A-linkage, A-windows, T-lang, disposition-merge, finished-final-comment-period

#2532 RFC: Associated type defaults
  text/2532-associated-type-defaults.md
Labels: A-associated-types, A-defaults, A-impls, A-traits, A-typesystem, T-lang, disposition-merge, finished-final-comment-period

#2646 Add more examples for | patterns in let in RFC 2175
  text/2175-if-while-or-patterns.md
Labels: A-control-flow, T-lang, not-rfc
