Repository rust-lang/rfcs, pull requests merged in 2020-02, with the labels that each got.

#2863 Added missing backtick
  text/0195-associated-items.md
Labels: not-rfc

#2396 target_feature 1.1
  text/0000-target-feature-1.1.md
Labels: A-effects, A-target_feature, A-typesystem, T-lang, disposition-merge, finished-final-comment-period

#2857 Rust 2020 roadmap
  text/0000-roadmap-2020.md
Labels: T-core, disposition-merge, finished-final-comment-period

#2868 Correct grammar in RFC 2857
  text/2857-roadmap-2020.md
Labels: not-rfc
