Repository rust-lang/rfcs, pull requests merged in 2020-10, with the labels that each got.

#2987 RFC 2582: fix implicit auto-deref of raw pointers
  text/2582-raw-reference-mir-operator.md
Labels: T-lang, not-rfc

#2998 2497: fix typo
  text/2497-if-let-chains.md
Labels: not-rfc

#3001 Fix typo in 2867
  text/2867-isa-attribute.md
Labels: not-rfc

#2959 RFC: Promote aarch64-unknown-linux-gnu to a Tier-1 Rust target
  text/0000-promote-aarch64-unknown-linux-gnu-to-tier1.md
Labels: A-target, T-compiler, T-infra, T-release, disposition-merge, finished-final-comment-period, to-announce

#2705 Amend RFC2603 to allow mangled identifiers to start with a digit.
  text/2603-rust-symbol-name-mangling-v0.md
Labels: I-nominated, T-compiler

#2909 Destructuring assignment
  text/0000-destructuring-assignment.md
Labels: T-lang, disposition-merge, finished-final-comment-period, to-announce

#2930 RFC: Reading into uninitialized buffers
  text/0000-read-buf.md
Labels: A-io, A-raw-pointers, Libs-Tracked, T-libs, disposition-merge, finished-final-comment-period, to-announce
