Repository rust-lang/rfcs, pull requests merged in 2020-12, with the labels that each got.

#3030 Fix link to tracing issue in RFC 2963
  text/2963-rustdoc-json.md
Labels: not-rfc

#2730 Fetching cargo registry tokens from external processes
  text/2730-cargo-token-from-process.md
Labels: A-registry, A-security, T-cargo, disposition-merge, finished-final-comment-period, to-announce

#3029 Fix incorrect sentence in RFC 2094
  text/2094-nll.md
Labels: not-rfc

#3017 Update example in RFC 2345 to have format argument
  text/2345-const-panic.md
Labels: not-rfc

#3008 fix incorrect cargo environment variable in 2141
  text/2141-alternative-registries.md
Labels: not-rfc

#2938 Readme fixes
  README.md
Labels: not-rfc

#2957 Stabilize Cargo's new feature resolver
  text/2957-cargo-features2.md
Labels: T-cargo, disposition-merge, finished-final-comment-period, to-announce
