Repository rust-lang/rfcs, pull requests merged in 2020-07, with the labels that each got.

#2873 Inline assembly
  text/0000-inline-asm.md
Labels: A-ASM, T-lang, disposition-merge, finished-final-comment-period

#2867 RFC: Add a new `#[instruction_set(...)]` attribute for supporting per-function instruction set changes
  text/0000-isa-attribute.md
Labels: A-attributes, A-target, A-target_feature, T-lang, disposition-merge, finished-final-comment-period

#2945 RFC: 'C-unwind' ABI
  text/0000-c-unwind-abi.md
Labels: A-ffi, A-panic, T-lang, disposition-merge, finished-final-comment-period
