Repository rust-lang/rfcs, pull requests merged in 2020-01, with the labels that each got.

#2835 Announcing the Safe-Transmute Project Group
  text/0000-project-safe-transmute.md
Labels: T-lang, disposition-merge, finished-final-comment-period

#2795 Propose implicit named arguments for formatting macros
  text/0000-format-args-implicit-identifiers.md
Labels: A-fmt, A-macros-libstd, T-lang, T-libs, disposition-merge, finished-final-comment-period

#2858 Fix incorrect links in existential types document
  text/2071-impl-trait-existential-types.md
Labels: not-rfc

#2700 Deprecate stdlib modules dedicated to numeric constants and move those constants to associated consts
  text/2700-associated-constants-on-ints.md
Labels: A-const, T-libs, disposition-merge, finished-final-comment-period
