Repository rust-lang/rfcs, pull requests merged in 2021-02, with the labels that each got.

#3037 Rust 2021 Roadmap
  text/3037-roadmap-2021.md
Labels: T-core, disposition-merge, finished-final-comment-period, to-announce

#3073 Mark 2203 as mostly superceeded by 2920
  text/2203-const-repeat-expr.md
Labels: I-nominated, T-lang, not-rfc

#3076 Fix link in RFC 1445
  text/1445-restrict-constants-in-patterns.md
Labels: not-rfc

#3077 Fix the link of RFC 1414 in RFC 2920
  text/2920-inline-const.md
Labels: not-rfc

#3070 Use more common 'tests' module name over 'test' in examples
  text/0505-api-comment-conventions.md
  text/1574-more-api-documentation-conventions.md
Labels: not-rfc

#3013 RFC: Checking conditional compilation at compile time
  text/3013-conditional-compilation-checking.md
Labels: T-cargo, T-compiler, disposition-merge, finished-final-comment-period, to-announce
