Repository rust-lang/rfcs, pull requests merged in 2021-03, with the labels that each got.

#3091 not-rfc: Fix a link in rfc-1096
  text/1096-remove-static-assert.md
Labels: not-rfc

#2951 Linking modifiers for native libraries
  text/0000-native-link-modifiers.md
Labels: A-ffi, A-linkage, T-compiler

#3052 Make the authors field optional
  text/0000-optional-authors-field.md
Labels: I-nominated, T-cargo, T-crates-io, disposition-merge, finished-final-comment-period, to-announce

#3086 RFC: Declarative macro metavariable expressions
  text/0000-macro-metavar-expr.md
Labels: A-macros, T-lang, disposition-merge, finished-final-comment-period, to-announce
