Repository rust-lang/rfcs, pull requests merged in 2021-04, with the labels that each got.

#2841 RFC: -C export-executable-symbols
  text/2841-export-executable-symbols.md
Labels: A-ffi, T-compiler, T-lang, disposition-merge, finished-final-comment-period, to-announce

#3109 Update RFC 243 to use Rust code blocks
  text/0243-trait-based-exception-handling.md
Labels: not-rfc

#3058 try_trait_v2: A new design for the ? desugaring
  text/3058-try-trait-v2.md
Labels: T-lang, T-libs, disposition-merge, finished-final-comment-period, to-announce

#2803 Target tier policy
  text/0000-target-tier-policy.md
Labels: T-compiler, T-infra, T-release, disposition-merge, finished-final-comment-period, to-announce
