Repository rust-lang/rfcs, pull requests merged in 2021-11, with the labels that each got.

#3176 Multiple artifact deps on the same crate with different names, for different targets
  text/3028-cargo-binary-dependencies.md
  text/3176-cargo-multi-dep-artifacts.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3180 Cargo `--crate-type` CLI Argument
  text/3180-cargo-cli-crate-type.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#2972 Constrained Naked Functions
  text/2972-constrained-naked.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3195 Fix link in RFC 2873
  text/2873-inline-asm.md
Labels: not-rfc

#3173 Add RFC float-next-up-down.
  text/3173-float-next-up-down.md
Labels: T-libs-api, finished-final-comment-period, disposition-merge, to-announce
