Repository rust-lang/rfcs, pull requests merged in 2021-07, with the labels that each got.

#3128 RFC: I/O Safety
  text/0000-io-safety.md
Labels: T-libs-api, disposition-merge, finished-final-comment-period, to-announce

#3137 RFC: let-else statements
  text/0000-let-else.md
Labels: T-lang, disposition-merge, final-comment-period, finished-final-comment-period, to-announce

#3107 `#[derive(Default)]` on enums with a `#[default]` attribute
  text/0000-derive-enum-default.md
Labels: A-derive, A-enum, T-lang, T-libs-api, disposition-merge, finished-final-comment-period, to-announce

#2509 RFC: Introduce `concat_bytes!()` to join `[u8]` and byte `str` analogous to `concat!` for `str`
  text/0000-byte-concat.md
Labels: A-macros-libstd, Libs-Tracked, T-libs-api, disposition-merge, finished-final-comment-period, to-announce

#3136 Switch from travis to github actions.
  .github/workflows/deploy.yml
  .travis.yml
Labels: not-rfc

#3143 Stabilize Cargo's weak-dep-features and namespaced-features.
  text/3143-cargo-weak-namespaced-features.md
Labels: T-cargo, disposition-merge, finished-final-comment-period, to-announce
