Repository rust-lang/rfcs, pull requests merged in 2021-05, with the labels that each got.

#3016 add const-ub RFC
  text/3016-const-ub.md
Labels: I-nominated, T-lang, disposition-merge, finished-final-comment-period, to-announce

#3101 RFC: Reserved prefixes in the 2021 edition
  text/3101-reserved_prefixes.md
Labels: T-lang, disposition-merge, finished-final-comment-period, to-announce

#3117 Change readme link for chat service.
  README.md
Labels: not-rfc

#3114 A new prelude for the 2021 edition (trait-only edition)
  text/0000-prelude-2021-traits.md
Labels: T-libs, disposition-merge, finished-final-comment-period, to-announce

#3085 RFC: 2021 Edition
  text/0000-edition-2021.md
Labels: T-core, disposition-merge, finished-final-comment-period, to-announce
