Repository rust-lang/rfcs, pull requests merged in 2021-01, with the labels that each got.

#2789 RFC: Serve crates-io registry over HTTP as static files
  text/2789-sparse-index.md
Labels: T-cargo, disposition-merge, finished-final-comment-period, to-announce

#3027 Infallible promotion
  text/3027-infallible-promotion.md
Labels: T-lang, disposition-merge, finished-final-comment-period, to-announce

#2992 RFC: Add `target_abi` configuration
  text/2992-cfg-target-abi.md
Labels: A-cfg, A-target, T-lang, disposition-merge, finished-final-comment-period, to-announce

#3007 RFC: Plan to make core and std's panic identical.
  text/0000-panic-plan.md
Labels: Libs-Tracked, T-lang, T-libs, disposition-merge, finished-final-comment-period, to-announce

#3065 Rename RFC 3007 Panic Plan
  text/3007-panic-plan.md
Labels: not-rfc

#3028 Allow "artifact dependencies" on bin, cdylib, and staticlib crates
  text/3028-cargo-binary-dependencies.md
Labels: I-nominated, T-cargo, disposition-merge, finished-final-comment-period, to-announce

#2580 RFC: Pointer metadata & VTable
  text/2580-ptr-meta.md
Labels: A-dst, A-repr, A-trait-object, A-traits, A-traits-libstd, A-types-libstd, Libs-Tracked, T-lang, T-libs, disposition-merge, finished-final-comment-period, to-announce
