Repository rust-lang/rfcs, pull requests merged in 2022-11, with the labels that each got.

#2432 0000-template.md: Encourage discussion of maintenance
  0000-template.md
Labels: I-nominated, T-core, A-meta

#2947 crates.io token scopes
  text/2947-crates-io-token-scopes.md
Labels: finished-final-comment-period, disposition-merge, A-security, T-crates-io, to-announce

#3345 Disable the playground run button by default for code blocks
  .github/workflows/deploy.yml
  book.toml
Labels: not-rfc

#3327 Add lang-team advisors team
  text/0000-lang-team-advisors.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3323 Restrictions
  text/3323-restrictions.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce
