Repository rust-lang/rfcs, pull requests merged in 2022-04, with the labels that each got.

#3248 tools: update checkout action on CI
  .github/workflows/deploy.yml
Labels: not-rfc

#3253 Fix link for prior-art in RFC3137
  text/3137-let-else.md
Labels: not-rfc

#3191 New Rust attribute to support embedding debugger visualizers
  text/3191-debugger-visualizer.md
Labels: T-lang, T-compiler, finished-final-comment-period, disposition-merge, to-announce

#3192 Add provide_any module to core
  text/3192-dyno.md
Labels: T-libs-api, finished-final-comment-period, disposition-merge, A-error-handling, to-announce, PG-error-handling

#3256 Fix broken links in RFC 1884
  text/1884-unstable-sort.md
Labels: not-rfc

#3258 Fix typo in RFC2071
  text/2071-impl-trait-existential-types.md
Labels: not-rfc
