Repository rust-lang/rfcs, pull requests merged in 2022-01, with the labels that each got.

#3215 FIXES #3214 generate-books.sh: ln --relative not supported on macOS
  generate-book.sh
Labels: not-rfc

#3219 Add a note to 2115 about un-accepting in-band
  text/2115-argument-lifetimes.md
Labels: T-lang, not-rfc

#3222 Fix typo in deprecation message for 2203
  text/2203-const-repeat-expr.md
Labels: not-rfc

#3151 Scoped threads in the standard library, take 2
  text/3151-scoped-threads.md
Labels: T-libs-api, finished-final-comment-period, disposition-merge, A-threads, to-announce
