Repository rust-lang/rfcs, pull requests merged in 2022-09, with the labels that each got.

#3315 Remove a redundant space
  text/2592-futures.md
Labels: not-rfc

#3307 De-RFC: Remove type ascription
  text/3307-de-rfc-type-ascription.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3309 Rust Style Team
  text/3309-style-team.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-formatting, to-announce

#3321 Add a note about the design change of RFC 2906 in implementation
  text/2906-cargo-workspace-deduplicate.md
Labels: T-cargo, not-rfc
