Repository rust-lang/rfcs, pull requests merged in 2022-12, with the labels that each got.

#3324 Support upcasting of `dyn Trait` values
  text/3324-dyn-upcasting.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3356 Update link to blog post
  text/1857-stabilize-drop-order.md
Labels: not-rfc

#3348 RFC: `c"…"` string literals
  text/3348-c-str-literal.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-syntax, to-announce
