Repository rust-lang/rfcs, pull requests merged in 2022-07, with the labels that each got.

#3273 Mention about removal of `crate` visibility specifier
  text/2126-path-clarity.md
Labels: T-lang

#3262 Rolling co-lead roles for T-compiler
  text/0000-compiler-team-rolling-leads.md
Labels: T-compiler, finished-final-comment-period, disposition-merge, to-announce

#3289 RFC: resolve crates.io source replacement ambiguity
  text/0000-source_replacement_ambiguity.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3297 Typo fixes in RFC 2856
  text/2856-project-groups.md
Labels: not-rfc
