Repository rust-lang/rfcs, pull requests merged in 2022-05, with the labels that each got.

#3229 Fix broken link
  text/1884-unstable-sort.md
Labels: not-rfc, T-libs

#3235 Edit README.md
  README.md
Labels: not-rfc

#3239 RFC: Add `target` configuration
  text/0000-cfg-target.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3216 Allow using `for<'a>` syntax when declaring closures
  text/0000-closure-lifetime-binder.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3254 Create a types team
  text/0000-types-team.md
Labels: T-lang, T-compiler, finished-final-comment-period, disposition-merge, to-announce

#3274 Update 1211-mir.md
  text/1211-mir.md
Labels: not-rfc
