Repository rust-lang/rfcs, pull requests merged in 2023-11, with the labels that each got.

#3498 Lifetime Capture Rules 2024
  text/3498-lifetime-capture-rules-2024.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3463 Add "crates.io Policy Update" RFC
  text/3463-crates-io-policy-update.md
Labels: finished-final-comment-period, disposition-merge, T-crates-io, to-announce

#3524 request/0.9.1 -> reqwest/0.9.1
  text/3463-crates-io-policy-update.md
Labels: not-rfc

#3516 RFC: Superseding public/private dependencies
  text/3516-public-private-dependencies.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024
