Repository rust-lang/rfcs, pull requests merged in 2023-01, with the labels that each got.

#3308 Add `core::mem::offset_of!` RFC
  text/3308-offset_of.md
Labels: T-libs-api, finished-final-comment-period, disposition-merge, to-announce

#3375 3192-dyno update plugin example
  text/3192-dyno.md
Labels: not-rfc

#3376 Mark Markdown files as linguist-detectable
  .gitattributes
Labels: not-rfc

#3346 Create an Operational Semantics Team
  text/3346-t-opsem.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, T-types
