Repository rust-lang/rfcs, pull requests merged in 2023-05, with the labels that each got.

#3389 Add a `[lints]` table to `Cargo.toml`
  text/3389-manifest-lint.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3127 New rustc and Cargo options to allow path sanitisation by default
  text/3127-trim-paths.md
Labels: T-compiler, T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3432 Fix some mentions of `--remap-path-prefix` that should be `--remap-path-scope`
  text/3127-trim-paths.md
Labels: not-rfc

#3433 Fix typos in RFC 0135
  text/0135-where.md
Labels: not-rfc

#3441 Fix autolink syntax on 3216
  text/3216-closure-lifetime-binder.md
Labels: not-rfc

#3424 eRFC: single-file packages ("cargo script") integration
  text/3424-cargo-script.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce
