Repository rust-lang/rfcs, pull requests merged in 2023-10, with the labels that each got.

#3507 Fix RFC numbers and pull request links
  text/0218-empty-struct-with-braces.md
  text/0326-restrict-xXX-to-ascii.md
  text/0601-replace-be-with-become.md
  text/1298-incremental-compilation.md
  text/1728-north-star.md
  text/2396-target-feature-1.1.md
  text/2436-style-guide.md
  text/2476-clippy-uno.md
  text/3327-lang-team-advisors.md
  text/3368-diagnostic-attribute-namespace.md
Labels: not-rfc

#3491 RFC: Remove implicit features in a new edition
  text/3491-remove-implicit-features.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3349 RFC: Unicode and escape codes in literals
  text/3349-mixed-utf8-literals.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-syntax, A-string, to-announce

#3453 Add `f16` and `f128` float types
  text/3453-f16-and-f128.md
Labels: T-lang, T-libs-api, finished-final-comment-period, disposition-merge, to-announce

#3501 2024 Edition
  text/3501-edition-2024.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-leadership-council
