Repository rust-lang/rfcs, pull requests merged in 2023-09, with the labels that each got.

#3399 Allow cfg-attributes in where clauses
  text/3399-cfg-attribute-in-where.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3477 Cargo Check T-lang Policy
  text/3477-cargo-check-lang-policy.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3499 Notify Zulip stream on types nominations
  triagebot.toml
Labels: not-rfc

#3500 Fix links in `triagebot.toml`
  triagebot.toml
Labels: not-rfc
