Repository rust-lang/rfcs, pull requests merged in 2024-09, with the labels that each got.

#3637 Guard Patterns
  text/3637-guard-patterns.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3690 fix some comments
  text/0339-statically-sized-literals.md
  text/0403-cargo-build-command.md
  text/1869-eprintln.md
  text/1990-external-doc-attribute.md
  text/2300-self-in-typedefs.md
  text/2361-dbg-macro.md
  text/2451-re-rebalancing-coherence.md
  text/2867-isa-attribute.md
  text/3389-manifest-lint.md
  text/3467-unsafe-pinned.md
  text/3550-new-range.md
Labels: not-rfc

#3662 Mergeable rustdoc cross-crate info
  text/0000-mergeable-rustdoc-cross-crate-info.md
Labels: T-rustdoc, finished-final-comment-period, disposition-merge, to-announce
