Repository rust-lang/rfcs, pull requests merged in 2024-01, with the labels that each got.

#3547 Make top-level special pages part of the web version of the book
  generate-book.py
Labels: not-rfc

#3551 Update guide on compiler RFCs
  compiler_changes.md
Labels: not-rfc

#3533 Add RFC combining Infra and Release teams
  text/3533-combine-infra-and-release-teams.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-leadership-council

#3493 RFC: Precise Pre-release `cargo update`
  text/3493-precise-pre-release-cargo-update.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3270 Mention RFC 1201 was superseded by RFC 2972
  text/1201-naked-fns.md
Labels: T-lang, not-rfc

#3535 RFC: constants in patterns
  text/0000-constants-in-patterns.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-patterns, A-const, to-announce

#3373 Avoid non-local definitions in functions
  text/3373-avoid-nonlocal-definitions-in-fns.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, T-types
