Repository rust-lang/rfcs, pull requests merged in 2024-07, with the labels that each got.

#3621 RFC: #[derive(SmartPointer)]
  text/3621-derive-smart-pointer.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3654 RFC: Return Type Notation
  text/3654-return-type-notation.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3627 Match ergonomics 2024
  text/3627-match-ergonomics-2024.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-patterns, to-announce, I-lang-nominated, A-edition-2024

#3514 add float semantics RFC
  text/3514-float-semantics.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3672 RFC for project goals
  text/3672-Project-Goals-2024h2.md
Labels: T-lang, T-libs-api, T-compiler, final-comment-period, T-cargo, T-rustdoc, T-infra, T-crates-io, T-libs, T-types, T-edition
