Repository rust-lang/rfcs, pull requests merged in 2024-06, with the labels that each got.

#3617 Precise capturing
  text/3617-precise-capturing.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3467 UnsafePinned: allow aliasing of pinned mutable references
  text/3467-unsafe-pinned.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, T-opsem

#3646 Change crates.io policy to not offer crate transfer mediation
  text/3646-remove-crate-transfer-mediation-policy.md
Labels: finished-final-comment-period, disposition-merge, T-crates-io, to-announce

#3416 RFC: Unblock Cargo feature metadata
  text/3416-feature-metadata.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce
