Repository rust-lang/rfcs, pull requests merged in 2024-04, with the labels that each got.

#3513 Add `gen` blocks and reserve keyword in Rust 2024
  text/3513-gen-blocks.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024

#3612 Update 2289-associated-type-bounds.md
  text/2289-associated-type-bounds.md
Labels: not-rfc

#3613 chore: remove repetitive words
  text/1298-incremental-compilation.md
  text/1398-kinds-of-allocators.md
  text/2091-inline-semantic.md
  text/2203-const-repeat-expr.md
  text/2585-unsafe-block-in-unsafe-fn.md
  text/2603-rust-symbol-name-mangling-v0.md
  text/3308-offset_of.md
  text/3535-constants-in-patterns.md
Labels: not-rfc

#3503 RFC: Syntax for embedding cargo-script manifests
  text/3503-frontmatter.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#2872 rust-lang org GitHub access policy
  text/2872-github-access-policy.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-leadership-council

#3595 Move the Crates.io Team under the Dev Tools team
  text/3595-move-crates-io-team-under-dev-tools.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-leadership-council

#3614 experimental project goal program for 2024 H2
  text/3614-project-goals.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-leadership-council, I-council-nominated
