Repository rust-lang/rfcs, pull requests merged in 2024-12, with the labels that each got.

#3734 Update 1946-intra-rustdoc-links.md
  text/1946-intra-rustdoc-links.md
Labels: not-rfc

#3691 crates.io: Trusted Publishing Support
  text/3691-trusted-publishing-cratesio.md
Labels: finished-final-comment-period, disposition-merge, T-crates-io, to-announce

#3591 Add support for `use Trait::func`
  text/3591-import-trait-associated-functions.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3722 [RFC] Explicit ABI in `extern`
  text/3722-explicit-extern-abis.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-defaults, to-announce, A-maybe-future-edition, T-edition
