Repository rust-lang/rfcs, pull requests merged in 2024-11, with the labels that each got.

#3692 RFC: Give users control over feature unification
  text/3692-feature-unification.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3681 [RFC] Default field values
  text/3681-default-field-values.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, I-lang-nominated

#3728 Fix minor typo in 3681-default-field-values.md
  text/3681-default-field-values.md
Labels: not-rfc

#3731 crates.io: Remove version deletions from the "crate deletions" RFC
  text/3660-crates-io-crate-deletions.md
Labels: T-crates-io
