Repository rust-lang/rfcs, pull requests merged in 2024-05, with the labels that each got.

#3519 Arbitrary self types v2
  text/3519-arbitrary-self-types-v2.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3606 RFC: Drop temporaries in tail expressions before local variables
  text/3606-temporary-lifetimes-in-tail-expressions.md
Labels: T-lang, finished-final-comment-period, disposition-merge, A-drop, A-ergonomics, to-announce, A-edition-2024

#3593 RFC: Reserve unprefixed guarded string literals in Edition 2024
  text/3593-unprefixed-guarded-strings.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024

#3325 unsafe attributes
  text/3325-unsafe-attributes.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce

#3636 Add diagram back to RFC 3606.
  text/3606-temporary-lifetimes-in-tail-expressions.md
  text/3606-temporary-lifetimes-in-tail-expressions/diagram.svg
Labels: not-rfc

#3502 RFC: cargo-script
  text/3502-cargo-script.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce

#3484 Unsafe Extern Blocks
  text/3484-unsafe-extern-blocks.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024

#3550 RFC: New range types for Edition 2024
  text/3550-new-range.md
Labels: T-lang, T-libs-api, finished-final-comment-period, disposition-merge, to-announce, I-types-nominated, A-edition-2024

#3336 MaybeDangling
  text/3336-maybe-dangling.md
Labels: T-lang, finished-final-comment-period, disposition-merge, to-announce
