Repository rust-lang/rfcs, pull requests merged in 2024-02, with the labels that each got.

#3558 eRFC: Iterate on and stabilize libtest's programmatic output
  text/3558-libtest-json.md
Labels: finished-final-comment-period, disposition-merge, to-announce, T-testing-devex

#3566 Update actions versions
  .github/workflows/deploy.yml
Labels: not-rfc

#3565 Update mdbook to 0.4.37
  .github/workflows/deploy.yml
  book.toml
Labels: not-rfc

#3568 Add renovatebot config file
  .github/renovate.json5
  .github/workflows/deploy.yml
Labels: not-rfc

#3509 RFC: Include `Future` and `IntoFuture` in the 2024 prelude
  text/3509-prelude-2024-future.md
Labels: T-libs-api, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024

#3574 update future prelude RFC with feedback from review
  text/3509-prelude-2024-future.md
Labels: not-rfc

#3537 RFC: Make Cargo respect minimum supported Rust version (MSRV) when selecting dependencies
  text/3537-msrv-resolver.md
Labels: T-cargo, finished-final-comment-period, disposition-merge, to-announce, A-edition-2024
