Repository rust-lang/rfcs, pull requests merged in 2024-03, with the labels that each got.

#3243 RFC: Packages as (optional) namespaces
  text/3243-packages-as-optional-namespaces.md
Labels: finished-final-comment-period, disposition-merge, T-crates-io, to-announce

#3584 remove repetitive words
  text/0458-send-improvements.md
  text/1214-projections-lifetimes-and-wf.md
  text/1252-open-options.md
  text/1721-crt-static.md
  text/1892-uninitialized-uninhabited.md
  text/2027-object_safe_for_dispatch.md
  text/2044-license-rfcs.md
  text/2226-fmt-debug-hex.md
  text/2535-or-patterns.md
  text/2795-format-args-implicit-identifiers.md
  text/2957-cargo-features2.md
  text/3127-trim-paths.md
  text/3308-offset_of.md
Labels: not-rfc

#3589 Correct rustdoc JSON example
  text/2963-rustdoc-json.md
Labels: not-rfc

#3590 Fix "higher kinded" -> "higher ranked" in RFC 3498
  text/3498-lifetime-capture-rules-2024.md
Labels: not-rfc

#3543 RFC: patchable-function-entry
  text/3543-patchable-function-entry.md
Labels: T-lang, T-compiler, finished-final-comment-period, disposition-merge, to-announce

#3580 provenance RFC: add link to alternative LLVM proposal
  text/3559-rust-has-provenance.md
Labels: not-rfc

#3598 chore: fix some comments
  text/0461-tls-overhaul.md
  text/0494-c_str-and-c_vec-stability.md
  text/1044-io-fs-2.1.md
  text/1414-rvalue_static_promotion.md
  text/2044-license-rfcs.md
  text/3509-prelude-2024-future.md
  text/3543-patchable-function-entry.md
Labels: not-rfc
