Repository rust-lang/rfcs, pull requests merged in 2025-03, with the labels that each got.

#3771 RFC: Demote i686-pc-windows-gnu to Tier 2
  text/3771-demote-i686-pc-windows-gnu.md
Labels: T-compiler, finished-final-comment-period, disposition-merge, T-release, to-announce

#3788 Fix start date for RFC 3771
  text/3771-demote-i686-pc-windows-gnu.md
Labels: not-rfc

#3631 RFC for doc_cfg, doc_cfg_auto, doc_cfg_hide and doc_cfg_show features
  text/000-rustdoc-cfgs-handling.md
Labels: T-rustdoc, finished-final-comment-period, disposition-merge, to-announce
